jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
#  port: 8081
  port: 8080
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/supportportal # database name
    url: jdbc:mysql://localhost:3306/hd # database name
    password: dunglh # SQL password
    username: sa # SQL username
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false # if wrong address then self-handle exception(ignore handle exception by Spring)